### ISSUE TITLE
All css classes must be kebab-case

### ISSUE THREAD

**Issue by Sojaner** [MedialightSweden/Go-light#1]
https://github.com/MedialightSweden/Go-light/blob/4a74d61c6f059ef7dc9e46ba0881038f9f5ab1e6/css/style.css#L16

The `Welcome` class starts with big letter.

* Kebab case: http://wiki.c2.com/?KebabCase

**Comment by Sojaner** [comment]
https://github.com/MedialightSweden/Go-light/blob/4a74d61c6f059ef7dc9e46ba0881038f9f5ab1e6/index.html#L19

**Comment by ShivaKalantar** [comment]
Alright 👍
