### ISSUE TITLE
The full width column should be 12 columns width

### ISSUE THREAD

**Issue by Sojaner** [MedialightSweden/Go-light#2]
https://github.com/MedialightSweden/Go-light/blob/4a74d61c6f059ef7dc9e46ba0881038f9f5ab1e6/index.html#L22

This should be `col-md-12` unless you did it intentionally.

**Comment by Sojaner** [comment]
Also, try the `.container-fluid` container instead of `.container` and see if it suits the website better.

**Comment by ShivaKalantar** [comment]
Yes,I understand . because Amanda has used max-width for paragraphs , I had to use a grid system to make it exactly look like what we have in design. but now I change the classes.
